name: Go

on:
  push:
    branches: [ "aula-actions-1" ]
  pull_request:
    branches: [ "aula-actions-1" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build do Banco
      run: docker-compose build
      
    - name: Roda o Banco
      run: docker-compose up –d
